spring:
  application:
    name: zentra-flow
  profiles:
    active: dev
  config:
    import: "optional:file:.env[.properties]"

  flyway:
    enabled: true
    locations: classpath:db/migration

zentra-flow:
  security:
    max-login-attempts: 5
    lockout-duration-minutes: 15

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc: DEBUG
