ALTER TABLE drivers ADD COLUMN cep VARCHAR(9);
ALTER TABLE drivers ADD COLUMN street VARCHAR(150);
ALTER TABLE drivers ADD COLUMN number VARCHAR(10);
ALTER TABLE drivers ADD COLUMN neighborhood VARCHAR(100);
ALTER TABLE drivers ADD COLUMN city VARCHAR(100);
ALTER TABLE drivers ADD COLUMN uf VARCHAR(2);
ALTER TABLE drivers ADD COLUMN complement VARCHAR(100);